version: '3'

services:
  todoapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000"

  todoweb:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - TodoApiService__EndpointUri=todoapi:5000
    ports:
      - "3000"
